name: iOS CI

on:
  push:
    branches: [ master-x ]
  pull_request:
    branches: [ master-x ]

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        brew install boost ninja xcodegen
    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v1.1.2
      with:
        path: build/local
        key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
      if: steps.internal_cache.outputs.cache-hit != 'true'
    - name: Run codegen tests
      run: tools/codegen-test
    - name: Run iOS tests
      run: |
        tools/generate-files
        # tools/ios-test
    - name: Build sample app
      run: |
        tools/samples-build ios
    - name: Build artifacts
      run: |
        tools/ios-build
    - uses: actions/upload-artifact@v2
      # if: github.ref == 'refs/heads/master-x'
      with:
        name: ios-libs
        path: |
          build/ios/libprotobuf.a
          build/ios/libTrezorCrypto.a
          build/ios/libTrustWalletCore.a
          .
